### ISSUE TITLE
Offset Feature Request

### ISSUE THREAD

**Issue by GaddMaster** [mattjarzeb/react-cloudinary-lazy-image#12]
Hi

Would it be a hard job add an offset for the intersect observer

If this was a param it would make this package even better.

Now I would try to do it myself, but I am almost certain I'll cause more trouble than its worth.
I am not quite there yet.

The reason for this would be that the image starts to load just before it intersects. Which is a great addition as an option

Daniel

**Comment by GaddMaster** [comment]
I do really appliance your package. it's great.

Hopefully we lower humans are not bothering you :( when I say "BUMP" :)

**Comment by mattjarzeb** [comment]
Sorry for the long response. Added in v1.3.2.
