### ISSUE TITLE
q_auto wrongly set if quality prop value is string

### ISSUE THREAD

**Issue by maja55** [mattjarzeb/react-cloudinary-lazy-image#13]
https://github.com/mattjarzeb/react-cloudinary-lazy-image/blob/aaaf5b8e8915abcdbbb52240a97a73cb64c64fb9/src/index.js#L13

Issue: 
Linked block currently concats to `q_auto:` if value includes `q_auto:`
`quality="q_auto:good"` => `q_auto:q_auto:good`
`quality="good"` => `good`
Expected is the other way around.

Solution: 
Just swap expressions in ternary operator

**Comment by mattjarzeb** [comment]
Thanks. Fixed in v1.3.2
