### ISSUE TITLE
Add the ability to modify urlParams of the placeholder.

### ISSUE THREAD

**Issue by yassinebridi** [mattjarzeb/react-cloudinary-lazy-image#3]
We can only change the urlParams of the image itself.
i want to add more blur to the placeholder, but there is no such setting.

**Comment by mattjarzeb** [comment]
What do you mean by 'add more blur to the placeholder'? 
We make the effect by loading image with width equal to 20px and keeps the aspect ratio. When the original image is loaded we show it (with transition-duration 0.5s when _fadeIn_ prop is set to true). To increase the blur effect we can decrease the first image size. Right now, you are right,  there is no such setting. Do you like to have an option to control it?

Another topic is placeholder styling. If you want to style placeholder use _placeholderStyle_ property.

**Comment by yassinebridi** [comment]
The overall flow of how images transition between blurred and not blured is perfect.
what i need is to have a blurred images with the quality of what medium has.
if you notice medium has a different and much better way of blurring images.
the way react-cloudinary-lazy-image present blurred images look more or less pixelated rather then completely blurred.

**Comment by mattjarzeb** [comment]
I as can see, Medium is doing it in a different way. They are showing a grey placeholder until the original image is downloaded. Then they transition from blurred to the normal version. 
Here we change images from low pixels to hight quality. To achieve better effect you can try adding:
`placeholderStyle={{
    filter: 'blur(1rem)'
}}`

**Comment by yassinebridi** [comment]
I see, i will try the styles then, thanks @mattjarzeb
