### ISSUE TITLE
Version Paramater ?

### ISSUE THREAD

**Issue by GaddMaster** [mattjarzeb/react-cloudinary-lazy-image#5]
This is a CND API with version numbers.

There sometimes crucial for app operation. How will someone change their profile image?

How do we insert the version parameter ?

**Comment by mattjarzeb** [comment]
Hi, 
There is no dedicated way of adding a version now. You can use `urlParams` to have the same result by simply adding /<version> at the and of the params string.  I'll add another prop to handle it.

**Comment by GaddMaster** [comment]
I understand. Ill use params until you add the prop. I was looking at the code and seen it would be easy add the version prop.

**Comment by mattjarzeb** [comment]
Added in v.1.2.4.
