### ISSUE TITLE
Have to set Height Manually for all Images ?

### ISSUE THREAD

**Issue by GaddMaster** [mattjarzeb/react-cloudinary-lazy-image#6]
Hi

Normally with <img> in HTML, we set the width, and then the height of the image will auto set and push other children down. 

Another way at saying it. -> We set the width and it auto sets height, including the height of the parent div.

We can do this with this package?

Daniel

**Comment by mattjarzeb** [comment]
Hi,
yes, in Fluid unset height was resulting in 0 when rendered. Fixed in v.1.2.4.

**Comment by GaddMaster** [comment]
Sorry. I did rephrase the question. Is your answer still for the question?
