### ISSUE TITLE
Not Loading Images

### ISSUE THREAD

**Issue by GaddMaster** [mattjarzeb/react-cloudinary-lazy-image#8]
Hi again.

There is a bug of some sort.

On pages where I have listed on exactly same components show the same images, some show, some never. 

If you change tab or something and come back, there appear.  

Same goes on all pages with a handful of images.

Daniel

**Comment by GaddMaster** [comment]
Some observations 
Works I iPad(chrome, safari), desktop(Firefox)
Doesn’t work on my desktop(chrome), android(chrome)

**Comment by GaddMaster** [comment]
Here is an example for study.

This is our staging site.

https://arstage.herokuapp.com/

**Comment by GaddMaster** [comment]
OK, I have been working on it now stop to try figure out. I know now the issue. 

It's my fault.

I was trying to keep the image container aspect ratio the same even before the image loaded and in doing so was hiding the image so the intersect observer was not been triggered

Sorry man

And thanks very much

**Comment by mattjarzeb** [comment]
I was about to say this 😄 . I'll change default styling of parent div to `100%` width and height not to have this issue again.
