### ISSUE TITLE
I'm Back :)

### ISSUE THREAD

**Issue by GaddMaster** [mattjarzeb/react-cloudinary-lazy-image#9]
Is it me or does the first tiny fetch not include params such as "r_max" or "r_10".

I end up with a background on the first image, then ones after are rounded as expected.

Daniel

**Comment by mattjarzeb** [comment]
Hi Daniel,

Yes, that's true. I'll include it in next release.
For now, you can style your image throw `imgStyle` prop.

**Comment by GaddMaster** [comment]
Thanks

**Comment by GaddMaster** [comment]
Another curious question....

Is there anyways we could set how low res the initial <img> is.

I was thinking I would increase it very slightly if possible?

Thoughts?

Daniel

**Comment by GaddMaster** [comment]
Hiya. 

Using border-radius and overflow hidden causes issues because if we cannot see the image, it won't load.

So adding the params to the initial image has become important.

Daniel

**Comment by GaddMaster** [comment]
Have to push this package onto a live site today and pictures are loading wack :(

Need ya bro 🥇

**Comment by GaddMaster** [comment]
Another good point !!!

The onLoad function should only return when the final image quality is loaded?

Thoughts?

What use would that function be for the first blob low res smudge?

Daniel

**Comment by mattjarzeb** [comment]
Hi,
sorry for the long response. 

In v.1.2.6 I've added params to set Cloudinary URL params for blur version of images. 
I also added a way to change the size of the initial low-resolution image.

What's wrong with onLoad function? I don't understand

**Comment by GaddMaster** [comment]
Great News.

As for onLoad -> When is it called? On the first Blur image or the final Image?

It would make more sense if it were the final image. ??

Thoughts?

**Comment by mattjarzeb** [comment]
onLoad is passed to the full-size image tag to onLoad prop.

**Comment by GaddMaster** [comment]
Cool COol...

**Comment by GaddMaster** [comment]
@mattjarzeb Not really sure whats going on here.

useUrlParamsToBlur true = loads errors 

The error image URL is missing params such as w_600, and for this reason, break, the resources are not available 

Is this happening for you too?

Here are two examples

https://res.cloudinary.com/thearsenalreview/image/upload/f_auto,q_auto,ar_16:9,r_8/v1/library/clash-arsenal-vs-vitoria-de-guimaraes-illustration-version-two

https://res.cloudinary.com/thearsenalreview/image/upload/f_auto,q_auto,ar_16:9,r_8,w_600/v1/library/clash-arsenal-vs-vitoria-de-guimaraes-illustration-version-two

One works , one doesnt 

Daniel

**Comment by mattjarzeb** [comment]
It was breaking as you used `ar` param, but it shouldn't happen in the first place. Fixed in v.1.2.7.

**Comment by GaddMaster** [comment]
You're the Man. I'll be back (Terminator Emoticon)

**Comment by GaddMaster** [comment]
Are you certain onLoad doesnt get called with the blur images and only the final high res image?

Because from what I can tell thats impossible be true 

What we need is an onLoad that is only called when the final high res image is loaded ?

Daniel

**Comment by mattjarzeb** [comment]
Yes, I'm quite sure. If you want to be sure, please see code.

**Comment by GaddMaster** [comment]
Ok Thanks
